COMP: Fix compilation error due to missing cmath include
Build is failing on current Slicer extension dashboard:
error: ‘floor’ is not a member of ‘std’