COMP: Fix compilation error due to missing namespace
Build is failing on current Slicer extension dashboard:
"error: ‘floor’ was not declared in this scope"